### ISSUE TITLE
Reason for subordinate approach?

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/interface-java#1]
Hi Kevin

We are trying to use this layer in one of our Charms. I'm a bit surprised by how this layer is implemented. I thought I could just include this layer in a Charm and Java would install. However, it seems this layer requires a subordinate relationship to the unit where it will install Java. What is the reason for the subordinate approach?

Kind regards
Merlijn

**Comment by johnsca** [comment]
The reasoning behind this is that by using an interface and subordinate which manages Java, it allows you to very easily swap which JRE / JDK you're running against.  This could potentially make a difference in performance, particularly if you use a JRE optimized for the hardware you're on.

This is pattern is somewhat similar to tomcat and the webapp-container relation.

**Comment by merlijn-sebrechts** [comment]
Thanks for this answer, Cory! Wouldn't you be able to get the same behavior
with a config option in the layer? The config option would specify what
version of Java has to be deployed.. Or is the idea that other subordinate
Charms would install other java versions? For example an oracle java
subordinate Charm..?

Op vrijdag 12 februari 2016 heeft Cory Johns notifications@github.com het
volgende geschreven:

**Comment by johnsca** [comment]
Right, it's more for different Java vendors than versions.  We currently have an IBM JRE charm, and OpenJDK charm, and a Zulu8 Java charm which support this interface.

**Comment by merlijn-sebrechts** [comment]
Ok, I understand! Thanks!

Op vrijdag 12 februari 2016 heeft Cory Johns notifications@github.com het
volgende geschreven:
